<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="ButtonFunc" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-02-19">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_I1" Type="IX" Comment="" x="533.3333333333334" y="-1066.6666666666667">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I2" Type="IX" Comment="" x="533.3333333333334" y="-13.333333333333334">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I3" Type="IX" Comment="" x="533.3333333333334" y="1366.6666666666667">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="DigitalInput_I1.INIT" Comment="" dx1="933.3333333333334"/>
			<Connection Source="INIT" Destination="DigitalInput_I2.INIT" Comment="" dx1="933.3333333333334"/>
			<Connection Source="INIT" Destination="DigitalInput_I3.INIT" Comment="" dx1="933.3333333333334"/>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
